# Generated by Django 4.2.3 on 2023-10-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installed_App',
            fields=[
                ('machine_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('installed_apps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Running_Apps',
            fields=[
                ('machine_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('running_apps', models.TextField()),
            ],
        ),
    ]
