# Generated by Django 4.2.3 on 2023-10-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Host_Name', models.CharField(max_length=200, null=True)),
                ('OS_Name', models.CharField(max_length=200, null=True)),
                ('OS_Version', models.CharField(max_length=200, null=True)),
                ('OS_Manufacturer', models.CharField(max_length=200, null=True)),
                ('OS_Configuration', models.CharField(max_length=200, null=True)),
                ('Registered_Owner', models.CharField(max_length=200, null=True)),
                ('System_Manufacturer', models.CharField(max_length=200, null=True)),
                ('System_Model', models.CharField(max_length=200, null=True)),
                ('System_Boot_Time', models.CharField(max_length=200, null=True)),
                ('Original_Install_Date', models.CharField(max_length=200, null=True)),
                ('BIOS_Version', models.CharField(max_length=200, null=True)),
                ('Boot_Device', models.CharField(max_length=200, null=True)),
                ('System_Locale', models.CharField(max_length=200, null=True)),
                ('Input_Locale', models.CharField(max_length=200, null=True)),
                ('Time_Zone', models.CharField(max_length=200, null=True)),
                ('Total_Physical_Memory', models.CharField(max_length=200, null=True)),
                ('Available_Physical_Memory', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
